# Generated by Django 2.2.4 on 2021-01-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='aka',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='current_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
